require "veritas"
require "veritas-td/version"
require "veritas-td/parser/case_insensitive_str"
require "veritas-td/parser/associativity"
require "veritas-td/parser"
require "veritas-td/transform"
require "veritas-td/interpreter"
